CREATE TABLE IF NOT EXISTS Tasks (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Company VARCHAR(100) NOT NULL,
    Description VARCHAR(1000) NOT NULL,
    Creator VARCHAR(50) NOT NULL,
    Assignee VARCHAR(50) NOT NULL,
    ReportedDate DATE NOT NULL,
    DueDate DATE,
    Priority VARCHAR(10) NOT NULL,
    Status VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS ChecklistItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TaskId INTEGER NOT NULL,
    Description VARCHAR(1000) NOT NULL,
    IsCompleted BOOLEAN NOT NULL,
    DueDate DATE,
    FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Messages (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TaskId INTEGER NOT NULL,
    NameUser VARCHAR(50) NOT NULL,
    MessageText VARCHAR(1000) NOT NULL,
    Timestamp DATE NOT NULL,
    FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE
);
